version: '3.1'

services:

  redis:
    image: redis
    restart: always
    ports:
        - 6379:6379
        
  db:
    image: postgres
    restart: always
    ports:
        - 5432:5432
    environment:
      POSTGRES_PASSWORD: securePassword!123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080